[optimizer]
loss = 'mse'
# lr = 0.001

[validation]
params = ["gauss_thresh", "nms_size"]
gauss_thresh = [ 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.95,]
nms_size = [ 2, 3, 5, 7, 11,]
checkpoints = [ 40000, 50000, 60000, 70000, 80000, 90000, 100000, 110000, 120000, 160000]

[evaluation]
distance_limit = 9999
metric = 'confusion_matrix.hoefener.AP'
res_key = "volumes/markers"
use_linear_sum_assignment = false
detection = "hoefener"
summary = [ "confusion_matrix.hoefener.AP",]
do_detection = true
sparse = true

[postprocessing]
gauss_thresh = 0.75
nms_size = 5
surf_key = "volumes/pred_cp"

[training]
max_iterations = 160000
