[optimizer]
loss = 'mse'

[training]
folds = '12'
max_iterations = 50000

[validation]
fold = '3'
gauss_thresh = [0.5, 0.8, 0.95, 0.99]

[evaluation]
distance_limit = 3
metric = 'gt_pred/AP'
do_detection = true
sparse = true

[preprocessing]

[postprocessing]
params = ["gauss_thresh"]
gauss_thresh = 0.8
