[optimizer]
loss = 'mse'
# lr = 0.001

[validation]
params = ["gauss_thresh"]
gauss_thresh = [0.5, 0.7, 0.75, 0.8, 0.95]

[evaluation]
distance_limit = 9999
metric = 'confusion_matrix.AP'
do_detection = true
sparse = true

[postprocessing]
gauss_thresh = 0.75
surf_key = "volumes/pred_cp"
