[optimizer]
loss = 'mse'

[validation]
gauss_thresh = [0.5, 0.8, 0.95, 0.99]

[evaluation]
distance_limit = 9999
metric = 'gt_pred/AP'
do_detection = true
sparse = true

[postprocessing]
params = ["gauss_thresh"]
gauss_thresh = 0.75
