[model]
batch_normalize = false
dropout = false
warmup_steps = 5000
warmup_fac = 1280
cyclic_lr = false
cyclic_stepsize = 5000
# cyclic_offset = 4000
cyclic_mode = 'exp_range'

[optimizer]
optimizer = 'Adam'
use_nesterov = false
momentum = 0.9
loss = 'ssce'
lr = 0.0001

[postprocessing]
surf_key = "volumes/pred_threeclass"

[validation]
num_dilations = [ 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,]
fg_thresh = [ 0.99, 0.5, 0.5, 0.99, 0.5, 0.6, 0.7, 0.8, 0.9, 0.85, 0.95, 0.99,]
seed_thresh = [ 0.8, 0.8, 0.7, 0.8, 0.7, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8,]
checkpoints = [ 400000, 100000, 140000, 200000,]
