[optimizer]
loss = 'mse'

[validation]
fg_thresh = [-0.1, -0.05, 0.0]
seed_thresh = [-0.10, -0.13, -0.16, -0.19]

[postprocessing.watershed]
fg_thresh = 0.0
seed_thresh = -0.10
surf_key = "volumes/pred_sdt"
fgbg_key = "volumes/pred_sdt"
