[optimizer]
loss = 'ce'

[training]
folds = '12'

[validation]
fold = '3'
num_dilations = [1, 2]
fg_thresh = [0.5, 0.8, 0.95, 0.99]
seed_thresh = [0.8, 0.9, 0.98, 0.99]

[evaluation]
metric = 'confusion_matrix/th_0_5/AP'
res_key = 'volumes/watershed_seg_fg_dilated'
num_workers = 8

[preprocessing]

[postprocessing]
params = [ "num_dilations", "fg_thresh", "seed_thresh",]
num_dilations = 1
fg_thresh = 0.95
seed_thresh = 0.98
surf_key = "volumes/pred_affs"
fgbg_key = "volumes/pred_fgbg"
raw_key = "volumes/raw_cropped"
