[model]
do_tanh = false

[optimizer]
loss = 'mse'

[validation]
num_dilations = [ 1, 1, 1, 1, 1, 1, 1, 1, 1,]
fg_thresh = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
seed_thresh = [ -0.13, -0.14, -0.15, -0.16, -0.17, -0.18, -0.19, -0.11, -0.12,]
checkpoints = [ 40000, 50000, 60000, 70000, 80000, 90000, 100000, 110000, 120000, 160000]

[postprocessing]
fg_thresh = 0.0
seed_thresh = -0.10
surf_key = "volumes/pred_sdt"
fgbg_key = "volumes/pred_sdt"

[training]
max_iterations = 160000
