[optimizer]
loss = 'ssce'

[model]
batch_normalize = false
dropout = false
warmup_steps = false
warmup_fac = 1280
cyclic_lr = false
cyclic_stepsize = 5000
# cyclic_offset = 4000
cyclic_mode = 'exp_range'

[postprocessing]
surf_key = "volumes/pred_threeclass"
