[model]
do_tanh = false

[optimizer]
loss = 'mse'

[validation]
num_dilations = [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1]
fg_thresh = [ 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.0, 0.0, 0.0, 0.0]
seed_thresh = [ -0.1, -0.13, -0.16, -0.19, -0.21, -0.22, -0.23, -0.25, -0.13, -0.14, -0.15, -0.16]

[postprocessing]
fg_thresh = 0.0
seed_thresh = -0.10
surf_key = "volumes/pred_sdt"
fgbg_key = "volumes/pred_sdt"
