[optimizer]
loss = 'ssce'

[training]
folds = '12'

[validation]
fold = '3'

[evaluation]
metric = 'confusion_matrix/th_0_5/fscore'
res_key = 'volumes/watershed_seg_fg_dilated'
num_workers = 8

[preprocessing]

[postprocessing]

[postprocessing.watershed]
num_dilations = 1
fg_thresh = 0.95
seed_thresh = 0.98
surf_key = "volumes/pred_threeclass"
fgbg_key = "volumes/pred_fgbg"
raw_key = "volumes/raw_cropped"
