[optimizer]
loss = 'ssce'

[postprocessing]
surf_key = "volumes/pred_threeclass"

[validation]
num_dilations = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]
fg_thresh = [ 0.99, 0.5, 0.6, 0.7, 0.8, 0.9, 0.85, 0.95, 0.95, 0.9, 0.99, 0.95, 0.9,]
seed_thresh = [ 0.8, 0.7, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.7, 0.7, 0.7, 0.9, 0.9,]
checkpoints = [ 100000, 200000, 300000, 400000,]

[training]
max_iterations = 400000
